version: "3.8"

services:
  api:
    image: ghcr.io/SEU_USUARIO/vehicle-ingestion-api:latest
    container_name: vehicle-ingestion-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
