version: "3.8"

services:
  api:
    image: ghcr.io/gabisinhas/backend-insightglobal-application:latest
    container_name: backend-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
