type VehicleType {
  typeId: String!
  typeName: String!
}

type VehicleMake {
  makeId: ID!
  makeName: String!
  vehicleTypes: [VehicleType!]!
}

type VehicleData {
  identifier: String!
  totalMakes: Int!
  lastUpdated: DateTime!
  makes: [VehicleMake!]!
}

scalar DateTime

type Query {
  vehicles: VehicleData
}