name: Deploy API

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u gabisinhas --password-stdin

      - name: Build & Push
        run: |
          docker build -t ghcr.io/gabisinhas/backend-insightglobal-application:latest .
          docker push ghcr.io/gabisinhas/backend-insightglobal-application:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd app
            docker compose pull
            docker compose up -d
